'use strict';

module.exports =
  angular.module('angu', [
    require('angular-ui-router'), // ui.router
    require('angular-animate'),   // ngAnimate
    require('angular-aria'),      // ngAria
    require('angular-cookies'),   // ngCookie
    require('angular-local-storage'), // LocalStorage
    require('angular-resource'),    // ngResource
    require('angular-material'),
    //load extra external dependencies here, e.g.:
    //'ngAnimate',
    //html templates in $templateCache generated by Gulp:
    require('../../../tmp/templates').name,
    //useful directives, filters, services shared across the app
    require('../common').name,
    // must be in the correct order...
    require('./player').name,
    require('./address').name,
    require('./auth').name,
    require('./badge').name,
    require('./card').name,
    require('./friend').name,
    require('./order').name,
    require('./product').name,
    require('./profile').name,
    require('./search').name,
    require('./taxonomy').name,
    require('./wishlist').name
  ])
  .config(require('./states'));
